/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OffreImmobilier } from './offreImmobilier';


export interface OffreImmobilierResponse { 
    offreImmobilier?: OffreImmobilier;
    typeBienOptions?: Array<OffreImmobilierResponse.TypeBienOptionsEnum>;
    ameublementOptions?: Array<OffreImmobilierResponse.AmeublementOptionsEnum>;
    statutProprieteOptions?: Array<OffreImmobilierResponse.StatutProprieteOptionsEnum>;
    chambresOptions?: Array<OffreImmobilierResponse.ChambresOptionsEnum>;
    sallesDeBainOptions?: Array<OffreImmobilierResponse.SallesDeBainOptionsEnum>;
    ageProprieteOptions?: Array<OffreImmobilierResponse.AgeProprieteOptionsEnum>;
}
export namespace OffreImmobilierResponse {
    export type TypeBienOptionsEnum = 'MAISON' | 'APPARTEMENT' | 'VILLA' | 'LOFT';
    export const TypeBienOptionsEnum = {
        Maison: 'MAISON' as TypeBienOptionsEnum,
        Appartement: 'APPARTEMENT' as TypeBienOptionsEnum,
        Villa: 'VILLA' as TypeBienOptionsEnum,
        Loft: 'LOFT' as TypeBienOptionsEnum
    };
    export type AmeublementOptionsEnum = 'SEMI_EQUIPE' | 'NON_EQUIPE' | 'EQUIPE';
    export const AmeublementOptionsEnum = {
        SemiEquipe: 'SEMI_EQUIPE' as AmeublementOptionsEnum,
        NonEquipe: 'NON_EQUIPE' as AmeublementOptionsEnum,
        Equipe: 'EQUIPE' as AmeublementOptionsEnum
    };
    export type StatutProprieteOptionsEnum = 'DISPONIBLE' | 'NON_DISPONIBLE' | 'RESERVE';
    export const StatutProprieteOptionsEnum = {
        Disponible: 'DISPONIBLE' as StatutProprieteOptionsEnum,
        NonDisponible: 'NON_DISPONIBLE' as StatutProprieteOptionsEnum,
        Reserve: 'RESERVE' as StatutProprieteOptionsEnum
    };
    export type ChambresOptionsEnum = 'S1' | 'S2' | 'S3' | 'S4' | 'S5' | 'S6';
    export const ChambresOptionsEnum = {
        S1: 'S1' as ChambresOptionsEnum,
        S2: 'S2' as ChambresOptionsEnum,
        S3: 'S3' as ChambresOptionsEnum,
        S4: 'S4' as ChambresOptionsEnum,
        S5: 'S5' as ChambresOptionsEnum,
        S6: 'S6' as ChambresOptionsEnum
    };
    export type SallesDeBainOptionsEnum = 'B1' | 'B2' | 'B3' | 'B4' | 'B5' | 'B6';
    export const SallesDeBainOptionsEnum = {
        B1: 'B1' as SallesDeBainOptionsEnum,
        B2: 'B2' as SallesDeBainOptionsEnum,
        B3: 'B3' as SallesDeBainOptionsEnum,
        B4: 'B4' as SallesDeBainOptionsEnum,
        B5: 'B5' as SallesDeBainOptionsEnum,
        B6: 'B6' as SallesDeBainOptionsEnum
    };
    export type AgeProprieteOptionsEnum = 'MOINS_DE_1_AN' | 'MOINS_DE_3_ANS' | 'MOINS_DE_10_ANS' | 'PLUS_DE_10_ANS';
    export const AgeProprieteOptionsEnum = {
        MoinsDe1An: 'MOINS_DE_1_AN' as AgeProprieteOptionsEnum,
        MoinsDe3Ans: 'MOINS_DE_3_ANS' as AgeProprieteOptionsEnum,
        MoinsDe10Ans: 'MOINS_DE_10_ANS' as AgeProprieteOptionsEnum,
        PlusDe10Ans: 'PLUS_DE_10_ANS' as AgeProprieteOptionsEnum
    };
}


